name: PHP-CS-Fixer

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      -   name: Checkout
          uses: actions/checkout@v3

      -   name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: 8.1
            coverage: none
            tools: php-cs-fixer

      -   name: Run PHP-CS-Fixer
          run: php-cs-fixer fix --diff --dry-run --config=.php-cs-fixer.dist.php
